name: CI

on:
  push:
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
  workflow_dispatch: {} 
    

jobs: 
  build:
    name: ${{ matrix.target-platform}}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v5
        with: 
          path: Library
          key: Library-${{ matrix.unity-version }}-${{ matrix.target-platform }}
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with: 
          targetPlatform: ${{ matrix.target-platform}}
          projectPath: ''
          unityVersion: ${{ matrix.unity-version}}
          
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target-platform}}-${{ matrix.unity-version}}
          path: build/${{ matrix.target-platform}}
          
    strategy:
      matrix: 
        unity-version: 
          - 6000.3.9f1
        os:
          - windows-2022
        include:
          - os: windows-2022
            target-platform: StandaloneWindows64