name: Lint

on:
  push:
    paths:
      - 'Multiplayer-Roguelike.Backend/**'
      - 'Multiplayer-Roguelike.Shared/**'
      - 'Multiplayer-Roguelike.Unity/**'
  pull_request:
    paths:
      - 'Multiplayer-Roguelike.Backend/**'
      - 'Multiplayer-Roguelike.Shared/**'
      - 'Multiplayer-Roguelike.Unity/**'
  workflow_dispatch:

jobs:
  backend-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Multiplayer-Roguelike.Backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: dotnet format Multiplayer-Roguelike.Backend.sln --verify-no-changes
